services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    ports: 
      - 5435:5432  

  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8090:8069"
    stdin_open: true
    tty: true    
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    command: ["odoo","-c","/etc/odoo/odoo.conf","-d","db_hotel_management","-u","hotel_management"]
        
    volumes:
      - odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons 
      - ./addons2:/mnt/addons2
      - ./custom-addons:/mnt/addons3
      - ./odoo.conf:/etc/odoo/odoo.conf  
    restart: always    
volumes:
  odoo:
  postgres:

